### PR TITLE
Add fake speech modules to avoid using Google services

### PR DESCRIPTION
**Pull request by mfussi66**
This PR adds two new modules: `fakeGoogleSpeech` and `fakeGoogleSpeechProcess`, that can be used when it is not possible to use the original `googleSpeech` and `googleSpeechProcess` modules, since they rely on connection with Google. 
The fake modules do not perform any actions, they only make sure to open the ports needed by `managerTUG`. 
Nonetheless, a user could send an RPC to `fakeGoogleSpeechProcess` with a phrase, and it will return a positive reply.

Together with the fake modules, a docker image and compose file are added, so there can be a clearer separation. 

Keeping the PR in draft until https://github.com/robotology/assistive-rehab/pull/325 is merged, so I can rebase first.

### CODE REVIEW

**Comment by pattacini** [comment]
CI failed on Windows.

**Comment by pattacini** [comment]
The CI failure on Windows seems unrelated to this PR anyhow.

**Comment by mfussi66** [comment]
Yep, this is the error:
```

Failures
 - curl (exited 1) - curl not installed. An error occurred during installation:
 The remote server returned an error: (504) Gateway Timeout. Gateway Timeout

Enjoy using Chocolatey? Explore more amazing features to take your
experience to the next level at
 https://chocolatey.org/compare
Error: Process completed with exit code 1.
```

Maybe there's an upstream issue with Chocolatey?

**Comment by pattacini** [comment]
>Maybe there's an upstream issue with Chocolatey?

Maybe. It's a bit random anyway. I'll try to re-launch the failed jobs later.

**Review by pattacini — APPROVED** [review]
Awaiting the CI before squashing and merging the PR.

**Pull request merged**
